uspto3ps/config/routes.rb
Uspto3ps::Application.routes.draw do
  devise_for :users
  
  resources :papps do
      member do
        post :vote_up
        post :vote_down
      end
    end

  root :to => "home#index"
  match 'currapps' => 'papps#latestpubapps'
  match 'getcaptcha' => 'papps#getcaptcha'
  match 'postcaptchascrape' => 'papps#postcaptchascrape'
  match 'about' => "about#index"

end

uspto3ps/app/models/papp.rb
class Papp < ActiveRecord::Base
  acts_as_voteable
end

uspto3ps/app/controllers/papps_controller.rb
#PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
#Copyright (C) 2012 Michelle M. Koeth
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as
#published by the Free Software Foundation, either version 3 of the
#License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
class PappsController < ApplicationController
  # GET /papps
  # GET /papps.json
  
  def index
    @papps = Papp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papps }
    end
  end
  
  def vote_up
    begin
      current_user.vote_for(@papp = Papp.find(params[:id]))
      flash[:notice] = "Thanks for Voting!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    rescue ActiveRecord::RecordInvalid
      flash[:notice] = "Oh noes! Your vote didn't go through. Please note that you can't vote twice on the same app!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    end
  end
  
  def vote_down
    begin
      current_user.vote_against(@papp = Papp.find(params[:id]))
      flash[:notice] = "Thanks for Voting!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    rescue ActiveRecord::RecordInvalid
      flash[:notice] = "Oh noes! Your vote didn't go through. Please note that you can't vote twice on the same app!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    end
  end

  
  def getcaptcha
    ag = Mechanize.new
    page = ag.get("http://portal.uspto.gov/external/portal/pair")
    # We need the recaptcha URL which has the token we want - on the Public Pair page, this is the table
    # class=epoTableBorder. The third tr has the recaptcha URL
    rc_url = page.parser.xpath("//table[@class='epoTableBorder']/tr[3]/td[1]/script[2]/@src")
    # If we download the code returned from visiting the recaptcha URL, then we can get the image token
    # The image token can then be sent into the google recaptch API to return the challege image
    rcpage = ag.get(rc_url)
    # The rcpage.body will have a string of javascript. From this, we want the string that follows from "content : "
    token = rcpage.body.partition("challenge : ")[2]
    token = token.partition(",")[0]
    # Now get rid of starting and ending quotes
    token = token[1..(token.length-2)]
    session['tok'] = token
    # Get the recaptcha imageURL
    @recaptcha_imageURL = "http://www.google.com/recaptcha/api/image?c=" + token
    # new fix since image wont display in production - save locally to server
    rcimage = ag.get(@recaptcha_imageURL)
    @rcfn =   token[(token.length-6)..-1] + '.jpg'
    rcimagefile = rcimage.save('public/assets/'+@rcfn)
    #puts "Class of rcimage: " + @rcimage.filename
    getjss= page.body.partition('function getDossier() {')
    # We also need to save specifically the save form's action which is hidden up in the javascript
    sfactionin = page.body.index("document.save.action =  '/external/portal")
    session['sfactiontok'] = page.body[(sfactionin+25)..(sfactionin+331)]
    session['getdoscodes'] = getjss[2].partition('</script>')[0]
    jsreplace = page.body.partition('<script type="text/javascript" src="http://api.recaptcha.net/challenge?k=')[2]
    session['jsrep'] = jsreplace.partition('</script>')[0]
    #aFile = File.new("page.html", "w")
    #aFile.write(page.body)
    #aFile.close
    # USe the current_page function with the mechanize agent once it is reestablished by reloading the serialized cookie jar
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papps }
    end
  end
  
  def postcaptchascrape
    # app number to be lookedup entered by user
    appno = params[:appno]
    # What data from PAIR to get
    pairtab = params[:data2get]
    ag = Mechanize.new
    #ag.cookie_jar.load('cookies.yml')
    page = ag.get("http://portal.uspto.gov/external/portal/pair")
    getjss= page.body.partition('function getDossier() {')
    doscodes = getjss[2].partition('</script>')[0]
    # replace the new getDossier function with the previous one for which we have the captcha info
    page.body.sub(doscodes,session['getdoscodes'])
    # The javascript that deals with the captcha must be copied out and replaced in the new page. Then we also might need all the
    # hidden vars as well. This is the getDossier() function, and
    # <script type="text/javascript" src="http://api.recaptcha.net/challenge?k=..."></script>
    jsreplace = page.body.partition('<script type="text/javascript" src="http://api.recaptcha.net/challenge?k=')[2]
    page.body.sub(jsreplace.partition('</script>')[0], session['jsrep'])
    form = page.forms.first
    form['recaptcha_response_field'] = params[:recaptcharesponse]
    form['recaptcha_challenge_field'] = session['tok']
    resp = form.submit
    #aFile = File.new("resp.html", "w")
    #aFile.write(resp.body)
    #aFile.close
    # At this point, we are recaptcha'd thru into PAIR. Next up is submitting a patent app no to get the filewrapper
    # Originally I tried to submit the form using the patentpub no, but I was unable to successfully get the form to
    # search against publication number, so I switched to searching against the default patent app number
    form1 = resp.forms.first
    #form1.fields.each { |f| puts f.name }
    #form1.radiobutton_with(:value => "appId").uncheck
    #form1.radiobutton_with(:value => "pgPubsNo").check
    #form1.radiobutton_with(:value => "pgPubsNo").click
    #puts "Appno checked? is: " + form1.radiobutton_with(:value => "appId").checked?.to_s + " PubNo checked? is: " + form1.radiobutton_with(:value => "pgPubsNo").checked?.to_s
    # id is number_id, name is dosnum
    form1['dosnum'] = appno
    # Next submit the form by clicking the submit button
    form1['selecteddosnum'] = appno
    form1['dosnumber'] = appno
    form1['isSubmitted'] = "isSubmitted"
    form1['submitButtonClicked'] = "submitButtonClicked"
    form1['selectedApplication'] = 0 #document.save.AppSearchType.selectedIndex
    # This form will not post properly unless we set the form action from the session var
    form1.action = session['sfactiontok']
    form1['testHidden'] = 'appId'
    form1['public_selectedSearchOption'] = 'pair_applicationSearchoption'
    form1['is_pair_new_search'] = 'appId'
    form1['AppSearchType'] = 'appId'
    resp2 = form1.click_button
    #aFile = File.new("resp2.html", "w")
    #aFile.write(resp2.body)
    #aFile.close
    # Resp2 now has the first application data screen (app data tab) on it
    # To switch between any of the tabs on PAIR and get the data on those tabs, you need to set the following hidden vars
    # and then submit as shown below. To go to another tab, just set the selectedTab value to the tab you want
    # Application Data (default) = "detailstab"
    # Transaction History = "fileHistorytab"
    # Image File Wrapper = 'ifwtab'
    # Continuity Data = 'continuitytab'
    # Published Documents = 'pubdatestab'
    # Address & Attorney agent = 'Correspondencetab'
    # Display References = 'pair_displayDownloadReferences'
    # Here, I am going to look at the file history
    
    form2 = resp2.forms.third
    if form2.nil?
      # Then the Captcha Did not go through right - give the user a notice and send them back to the getcaptcha page
      flash[:notice] = "Please enter in a new captcha as shown - the other one was not accepted"
      redirect_to :back
    else
    form2['selectedTab'] = pairtab
    form2['isSubmitted'] = 'isSubmitted'
    # Get the action string from the page
    actstr = resp2.body.index("document.MainPage.action =  '")
    form2.action =  resp2.body[(actstr+29)..(actstr+359)]
    puts "form2 action is: " + resp2.body[(actstr+29)..(actstr+359)]
    form2['dosnum']= appno
    tab = form2.submit
    # Now we want to get the data out of the tab that is returned
    # - MVP grab the table data and send it to the view
    case pairtab
    when 'detailstab'
      @tabdata = tab.parser.xpath("//table[@id='bibview']").to_html
    when 'fileHistorytab'
      @tabdata = tab.parser.xpath("//table[@id='bibcontents']").to_html
    when 'ifwtab'
      @tabdata = tab.parser.xpath("//table[@id='ifwinnertable']").to_html
    when 'continuitytab'
      @tabdata = tab.parser.xpath("//table[@id='continuityparent']").to_html
    when 'pubdatestab'
      # this table doesn't have an id.. but its the first table will cellspacing = 1
      @tabdata = @tabdata = tab.parser.xpath("//table[@cellspacing='1']")[0].to_html
    when 'Correspondencetab'
      @tabdata = @tabdata = tab.parser.xpath("//table[@id='correspondence']").to_html
    when 'pair_displayDownloadReferences'
      @tabdata = @tabdata = tab.parser.xpath("//div[@id='ebchelp']").to_html
    else
      @tabdata = tab.parser.xpath("//table[@id='bibview']").to_html
    end
    
    #aFile = File.new("resp3.html", "w")
    #aFile.write(tab.body)
    #aFile.close
  end
    
  end
  
  def latestpubapps
    # see if there are already the latest published apps in the database
    today = Date.today
    # figure out what today is, then what day the last thursday was.. wday for thursday = 4
    if today.wday < 5
      lthurs = today - (today.wday + 3)
    else
      lthurs = today - (today.wday - 4)
    end

uspto3ps/app/helpers/papps_helper.rb
module PappsHelper
end

uspto3ps/app/views/papps/_form.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<%= form_for(@papp) do |f| %>
  <% if @papp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@papp.errors.count, "error") %> prohibited this papp from being saved:</h2>

      <ul>
      <% @papp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appno %><br />
    <%= f.text_field :appno %>
  </div>
  <div class="field">
    <%= f.label :firstinventorname %><br />
    <%= f.text_field :firstinventorname %>
  </div>
  <div class="field">
    <%= f.label :assignee %><br />
    <%= f.text_field :assignee %>
  </div>
  <div class="field">
    <%= f.label :filingdate %><br />
    <%= f.date_select :filingdate %>
  </div>
  <div class="field">
    <%= f.label :apptype %><br />
    <%= f.text_field :apptype %>
  </div>
  <div class="field">
    <%= f.label :examinername %><br />
    <%= f.text_field :examinername %>
  </div>
  <div class="field">
    <%= f.label :artunit %><br />
    <%= f.text_field :artunit %>
  </div>
  <div class="field">
    <%= f.label :confnumber %><br />
    <%= f.text_field :confnumber %>
  </div>
  <div class="field">
    <%= f.label :classsub %><br />
    <%= f.text_field :classsub %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :pubdate %><br />
    <%= f.date_select :pubdate %>
  </div>
  <div class="field">
    <%= f.label :firstoadate %><br />
    <%= f.date_select :firstoadate %>
  </div>
  <div class="field">
    <%= f.label :noadate %><br />
    <%= f.date_select :noadate %>
  </div>
  <div class="field">
    <%= f.label :issuedate %><br />
    <%= f.date_select :issuedate %>
  </div>
  <div class="field">
    <%= f.label :currstatus %><br />
    <%= f.text_field :currstatus %>
  </div>
  <div class="field">
    <%= f.label :currstatusdate %><br />
    <%= f.date_select :currstatusdate %>
  </div>
  <div class="field">
    <%= f.label :pubno %><br />
    <%= f.text_field :pubno %>
  </div>
  <div class="field">
    <%= f.label :pubrequest %><br />
    <%= f.check_box :pubrequest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

uspto3ps/app/views/papps/edit.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<h1>Editing papp</h1>

<%= render 'form' %>

<%= link_to 'Show', @papp %> |
<%= link_to 'Back', papps_path %>

uspto3ps/app/views/papps/getcaptcha.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<h2>Enter the Recaptcha to get USPTO data</h2>
<%= image_tag(@rcfn) %>
<%= form_tag("/postcaptchascrape", :method => "get") do %>
<%= label_tag(:recaptcharesponse, "Enter Response:") %>
  <%= text_field_tag(:recaptcharesponse) %>
  <P>
 <%= label_tag(:appno, "Enter A Patent Application Num to lookup:") %> 
    <%= text_field_tag(:appno) %>
  <P>
    <%= label_tag(:tab, "Pick which info you'd like from PAIR about this Patent App:") %>
    <p>
    <%= label_tag(:data2get, "Application Data(default):") %>
    <%= radio_button_tag 'data2get', 'detailstab', true %>
    <P>
    <%= label_tag(:data2get, "Status History:") %>
    <%= radio_button_tag 'data2get', 'fileHistorytab' %>
    <P>
    <%= label_tag(:data2get, "File Wrapper:") %>
    <%= radio_button_tag 'data2get', 'ifwtab' %>
    <P>
    <%= label_tag(:data2get, "Continuity Data:") %>
    <%= radio_button_tag 'data2get', 'continuitytab' %>
    <P>
    <%= label_tag(:data2get, "Publication Data:") %>
    <%= radio_button_tag 'data2get', 'pubdatestab' %>
    <P>
    <%= label_tag(:data2get, "Attorney/Correspondence Data:") %>
    <%= radio_button_tag 'data2get', 'Correspondencetab' %>
    <P>
    <%= label_tag(:data2get, "References of record:") %>
    <%= radio_button_tag 'data2get', 'pair_displayDownloadReferences' %>
    <P>
  <%= submit_tag("Continue") %>
  <% end %>
<%= link_to 'Back', papps_path %>

uspto3ps/app/views/papps/index.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<h1>Listing papps</h1>

<table>
  <tr>
    <th>Appno</th>
    <th>Firstinventorname</th>
    <th>Assignee</th>
    <th>Filingdate</th>
    <th>Apptype</th>
    <th>Examinername</th>
    <th>Artunit</th>
    <th>Confnumber</th>
    <th>Classsub</th>
    <th>Published</th>
    <th>Pubdate</th>
    <th>Firstoadate</th>
    <th>Noadate</th>
    <th>Issuedate</th>
    <th>Currstatus</th>
    <th>Currstatusdate</th>
    <th>Pubno</th>
    <th>Pubrequest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papps.each do |papp| %>
  <tr>
    <td><%= papp.appno %></td>
    <td><%= papp.firstinventorname %></td>
    <td><%= papp.assignee %></td>
    <td><%= papp.filingdate %></td>
    <td><%= papp.apptype %></td>
    <td><%= papp.examinername %></td>
    <td><%= papp.artunit %></td>
    <td><%= papp.confnumber %></td>
    <td><%= papp.classsub %></td>
    <td><%= papp.published %></td>
    <td><%= papp.pubdate %></td>
    <td><%= papp.firstoadate %></td>
    <td><%= papp.noadate %></td>
    <td><%= papp.issuedate %></td>
    <td><%= papp.currstatus %></td>
    <td><%= papp.currstatusdate %></td>
    <td><%= papp.pubno %></td>
    <td><%= papp.pubrequest %></td>
    <td><%= link_to 'Show', papp %></td>
    <td><%= link_to 'Edit', edit_papp_path(papp) %></td>
    <td><%= link_to 'Destroy', papp, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Papp', new_papp_path %>

uspto3ps/app/views/papps/latestpubapps.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<h1>Patent Applications Published on <%= @date %></h1>
<table border=1 cellpadding=5>
  <tr>
    <th><b>App number:</b></th>
    <th><b>Title:</b></th>
    <th><b>Link:</b></th>
  </tr>
<% @papps.each do | app | %>
<tr>
  <td>
    <%= link_to app.pubno, papp_path(app.id) %>
  </td>
  <td>
    <%= app.title %>
  </td>
  <td>
    <a href="<%=app.linktoapp%>"><%=app.linktoapp%></a>
  </td>
</tr>
<% end %>
</table>

<%= link_to 'Back', papps_path %>

uspto3ps/app/views/papps/new.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<h1>New papp</h1>

<%= render 'form' %>

<%= link_to 'Back', papps_path %>

uspto3ps/app/views/papps/postcaptchascrape.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<%= @tabdata.html_safe %>

uspto3ps/app/views/papps/show.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<p id="notice"><%= notice %></p>

<p>
  <b>Appno:</b>
  <%= @papp.appno %>
</p>

<p>
  <b>Firstinventorname:</b>
  <%= @papp.firstinventorname %>
</p>

<p>
  <b>Assignee:</b>
  <%= @papp.assignee %>
</p>

<p>
  <b>Filingdate:</b>
  <%= @papp.filingdate %>
</p>

<p>
  <b>Apptype:</b>
  <%= @papp.apptype %>
</p>

<p>
  <b>Examinername:</b>
  <%= @papp.examinername %>
</p>

<p>
  <b>Artunit:</b>
  <%= @papp.artunit %>
</p>

<p>
  <b>Confnumber:</b>
  <%= @papp.confnumber %>
</p>

<p>
  <b>Classsub:</b>
  <%= @papp.classsub %>
</p>

<p>
  <b>Published:</b>
  <%= @papp.published %>
</p>

<p>
  <b>Pubdate:</b>
  <%= @papp.pubdate %>
</p>

<p>
  <b>Firstoadate:</b>
  <%= @papp.firstoadate %>
</p>

<p>
  <b>Noadate:</b>
  <%= @papp.noadate %>
</p>

<p>
  <b>Issuedate:</b>
  <%= @papp.issuedate %>
</p>

<p>
  <b>Currstatus:</b>
  <%= @papp.currstatus %>
</p>

<p>
  <b>Currstatusdate:</b>
  <%= @papp.currstatusdate %>
</p>

<p>
  <b>Pubno:</b>
  <%= @papp.pubno %>
</p>

<p>
  <b>Pubrequest:</b>
  <%= @papp.pubrequest %>
</p>

<p>
  <b>Title:</b>
  <%= @papp.title %>
</p>

<p>
  <b>Link:</b>
  <%= @papp.linktoapp %>
</p>
<!-- add in link for Update against USPTO PAIR -->

<%= link_to 'Edit', edit_papp_path(@papp) %> |
<%= link_to 'Back', papps_path %>