uspto3ps/config/routes.rb
Uspto3ps::Application.routes.draw do
  devise_for :users
  
  resources :papps do
      member do
        post :vote_up
        post :vote_down
      end
    end

  root :to => "home#index"
  match 'currapps' => 'papps#latestpubapps'
  match 'getcaptcha' => 'papps#getcaptcha'
  match 'postcaptchascrape' => 'papps#postcaptchascrape'
  match 'about' => "about#index"

end

uspto3ps/app/controllers/home_controller.rb
#PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
#Copyright (C) 2012 Michelle M. Koeth
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as
#published by the Free Software Foundation, either version 3 of the
#License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
class HomeController < ApplicationController
  def index
    # Here we want to display the running board of applications and their popularity
    # first check for voted on apps, and rank. If less than 100, then add in as many non-voted apps to the end
    # of the list
    # Let users vote if they are logged in. If they are not logged in, let them simply see the popularity rankings
    #@toppapps = Papp.plusminus_tally.limit(100).where('created_at > ?', 2.days.ago).having('plusminus > 10')
    toppapps = Papp.plusminus_tally.limit(100).having('vote_count > 0').order('plusminus DESC')
    tahash = toppapps.size
    size = 0
    #puts "NUM OF VOTED PAPPS " + tahash.keys.count.to_s
    if toppapps.empty? {size = 0}
    else size = tahash.keys.count
    end
    if size < 100
      moreapps = Papp.tally.having('vote_count = 0').order('created_at DESC')
    end
    @papps = toppapps + moreapps
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papps }
    end
  end
end

uspto3ps/app/helpers/home_helper.rb
module HomeHelper
end

uspto3ps/app/views/home/index.html.erb
<% if false %>
PatentBat - A web platform for facilitating the third party submissions of prior art under 37 CFR 1.290
Copyright (C) 2012 Michelle M. Koeth

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<% end %>
<h2>Latest Pitches:</h2>
<table border=1 cellpadding=5>
  <tr>
    <th><b>Plusminus Ranking:</b></th>
    <th><b>App number:</b></th>
    <th><b>Title:</b></th>
    <th><b>Link:</b></th>
    <% if user_signed_in? %><th><b>Your Vote:</b></th><% end %>
  </tr>
<% @papps.sort_by(&:plusminus).reverse.each do | app | %>
<tr>
  <td>
    <%= app.plusminus %>
  </td>
  <td>
    <%= link_to app.pubno, papp_path(app.id) %>
  </td>
  <td>
    <%= app.title %>
  </td>
  <td>
    <a href="<%=app.linktoapp%>"><%=app.linktoapp%></a>
  </td>
  <% if user_signed_in? %>
    <td>
      <% if current_user.voted_on?(Papp.find(app.id)) %>
        <% if current_user.voted_for?(Papp.find(app.id)) %>
          Batter up! Lets take a swing at it!
        <% else %>
          Meh, nothing wrong with it.
        <% end %>
      <% else %>
        <%= link_to('Vote: This seems obvious! Lets take a swing at it!', vote_up_papp_path(app), :method => :post) %>
        <P>
        <%= link_to('Vote: Meh, seems novel and non-obvious.', vote_down_papp_path(app), :method => :post) %>
      <% end %>
    </td>
  <% end %>
</tr>
<% end %>
</table>